### ISSUE TITLE
Can you make a vertical slider?

### ISSUE THREAD

**Issue by thomasloven** [thomasloven/lovelace-slider-entity-row#126]
I get this request often.
Do you realize what you're asking? Because this is what it'd look like:
![image](https://user-images.githubusercontent.com/1299821/82651466-7c7ff780-9c1c-11ea-9993-6dd2667caafc.png)

If you still want it, you can get it with card-mod and `transform: rotate(-90deg)`, but it won't work well because the slider element used in Home Assistant isn't meant for vertical use.

**Comment by ktownsend-personal** [comment]
It sounds like the main limiting factor is the built-in slider control because it doesn't handle the input coordinates properly when it's been rotated. I think what we truly need is a from-scratch vertical slider control. I'm quite surprised there isn't one in the community already. Someday when I have time to ramp up on the prerequisites I may need to roll my own control.
