### ISSUE TITLE
Having 'closed' instead of 0%

### ISSUE THREAD

**Issue by smbunn** [thomasloven/lovelace-slider-entity-row#179]
I like the curtain in my cover saying 'Open' when the slider is at 100% but says 0% when the slide is at that position.  Can we have the option of setting it to say 'closed'?

**Comment by thierry-rhone** [comment]
Hi,
To extend the question. Is it possible chang the word "closed " depending on the user language

**Comment by prilly-dev** [comment]
Hey!!Dont be like a smart ass mister, here are guys using ha for years and know what is going on in their setups, recently modbus has made this instances unusable, its nothing to discuss, the problem is related to the recent update of modbus itself. But as mention here initialy, its difficult to log this, maybe provide a detailed explanation what you want.
-------- Opprinnelig melding --------Fra: thierry-rhone ***@***.***> Dato: 03.05.2021  14:23  (GMT+01:00) Til: thomasloven/lovelace-slider-entity-row ***@***.***> Ko: Subscribed ***@***.***> Emne: Re: [thomasloven/lovelace-slider-entity-row] Having 'closed' instead of 0% (#179) 
Hi,
To extend the question. Is it possible chang the word "closed " depending on the user language

**Comment by thomasloven** [comment]
Slider-entity-row will show Closed if the state of the `cover` entity is `closed`. If yours doesn't report that state, I suggest you report this as a bug or feature request as appropriate to the integration maintainer.
