### ISSUE TITLE
Media player volume muted when changing volume

### ISSUE THREAD

**Issue by haattis** [thomasloven/lovelace-slider-entity-row#181]
My Home Assistant version: 2021.3.4

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Clicking the slider

What I expected to happen:
Volume is set to selected level

What happened instead:
Volume is set to selected level, but a media_player.mute is called straight after.

**Minimal** steps to reproduce:

```yaml
      - type: custom:slider-entity-row
        entity: media_player.philips_tv
        name: Philips TV
```

Error messages from the browser console:
None
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by olexs** [comment]
I have a similar issue, even weirder in a way: when using the sliders to configure volume, it always is set to 62%. The slider then stops functioning - it can be moved to any position, the volume stays at 62%. Changing volume from the "more info" window or any other way works, and the slider reacts to state changes and updates to the correct position.

**Comment by olexs** [comment]
Adding to the above comment: I've since added a couple instances of the `slider-entity-row` with dimmable lights as entities. These work flawlessly, the issue only exists with the instances used for media volume control.

**Comment by Psychoses** [comment]
i have exactly the same issue.

> Volume is set to selected level, but a media_player.mute is called straight after.

**Comment by Psychoses** [comment]
I looked at the code a bit and the problem seems be localized here https://github.com/thomasloven/lovelace-slider-entity-row/blob/3865b001de4e00f3c869ceb099a11ab602885d7f/src/controllers/media-player-controller.ts#L22

So a temp fix can be :

- Connect in ssh or gui for edit `/config/www/community/lovelace-slider-entity-row` files

- Backup `slider-entity-row.js` file and gz

- Replace `volume_level:t}),t&&this._hass.callService("media_player","volume_mute",{entity_id:this.stateObj.entity_id,is_volume_muted:!1})}get isOff()` with `volume_level:t})}get isOff()` on `slider-entity-row.js`.

- Generate a new `slider-entity-row.js.gz` file with a tools of your choice.

- All done. Mute prob fixed.

**Comment by peledzius** [comment]
Facing same problem in Samsung TV.

**Comment by thomasloven** [comment]
This is actually an issue with the integrations for your specific `media_player`s, but...
