### ISSUE TITLE
color_temp in kelvins

### ISSUE THREAD

**Issue by spencerthayer** [thomasloven/lovelace-slider-entity-row#259]
Now that HA is kelvins by default can you create an option to chose mireds vs kelvin? Thanks!

**Comment by ChristophCaina** [comment]
would be cool, especially, if the device does support both modes :)
![grafik](https://user-images.githubusercontent.com/26391061/204916879-bb9fe2f0-d0a2-4d16-9643-12a1939e28e3.png)

Using the color_temperature_kelvin instead of the "regular" one, would also allow to add the "unit of measurement" indicating that the slider is for color temperature - when in "full row" mode...

![grafik](https://user-images.githubusercontent.com/26391061/204917162-92c989dc-8bed-4f9a-a681-73b16896e8ae.png)

**Comment by spencerthayer** [comment]
Thank you @thomasloven so much! I feel like you have given me the best Christmas gift of the year.
