### ISSUE TITLE
Custom element doesn't exist in Safari

### ISSUE THREAD

**Issue by mmalina** [thomasloven/lovelace-slider-entity-row#35]
Today I wanted to try a custom lovelace card for the first time and I liked yours. But after spending some time trying to make it work I came across this:
https://community.home-assistant.io/t/stuck-on-custom-element-doesnt-exist-need-help/73220/11
> Sounds to me like a browser issue since not all browsers support the custom element feature or latest javascript, which leads to some cards works and some dont.

And sure enough, it turns out your custom card works in Chrome, but not in Safari, which happens to be my main browser.

I'm not sure if it's feasible to add support for Safari, but perhaps you could consider adding a note to your readme. I can prepare a PR if you like.

**Comment by thomasloven** [comment]
I assure you custom elements (and slider-entity-row) works perfectly well in Safari
![Skärmavbild 2019-03-22 kl  21 18 35](https://user-images.githubusercontent.com/1299821/54850705-234ec800-4ce8-11e9-98b2-ca28734c4526.png)
and have done so since version 10.1 (released 2016-10-24). Mobile Safari as well.

Please read this guide for installation and debugging instructions: https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins

**Comment by mmalina** [comment]
Thank you, Thomas. And sorry, I'm not sure what happened, I swear it worked for me in Chrome but not Safari. Anyway, I tried again now and it works. I'm not aware of doing anything differently. Anyway, I must have done something wrong.

And BTW great job! This plugin is really awesome!

**Comment by thomasloven** [comment]
Eh. It happens.
